"""Sync database models

Revision ID: 41ae83315df9
Revises: 7970ab493fdc
Create Date: 2025-09-12 20:31:11.395842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41ae83315df9'
down_revision: Union[str, Sequence[str], None] = '7970ab493fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cases_status_type', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_calendar_events_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_calendar_sync_logs_id', table_name='calendar_sync_logs')
    op.drop_table('calendar_sync_logs')
    op.add_column('documents', sa.Column('final_serial_number', sa.Integer(), nullable=True, comment='最終系統流水號'))
    op.add_column('documents', sa.Column('source_serial_number', sa.Integer(), nullable=True, comment='來源CSV流水號'))
    op.alter_column('documents', 'doc_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='公文文號')
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False,
               comment='公文類型 (收文/發文)')
    op.alter_column('documents', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False,
               comment='主旨')
    op.alter_column('documents', 'sender',
               existing_type=sa.VARCHAR(length=200),
               comment='發文單位',
               existing_nullable=True)
    op.alter_column('documents', 'receiver',
               existing_type=sa.VARCHAR(length=200),
               comment='受文單位',
               existing_nullable=True)
    op.alter_column('documents', 'doc_date',
               existing_type=sa.DATE(),
               comment='發文日期 (西元)',
               existing_nullable=True)
    op.alter_column('documents', 'receive_date',
               existing_type=sa.DATE(),
               comment='收文日期 (西元)',
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='處理狀態 (例如：待處理, 已辦畢)',
               existing_nullable=True,
               existing_server_default=sa.text("'收文完成'::character varying"))
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               comment='公文內容摘要',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='建立時間',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最後更新時間',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'send_date',
               existing_type=sa.DATE(),
               comment='發文日期 (用於區分 doc_date)',
               existing_nullable=True)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='公文分類 (例如：行政, 業務)',
               existing_nullable=True)
    op.alter_column('documents', 'contract_case',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               comment='承攬案件名稱或編號',
               existing_nullable=True)
    op.alter_column('documents', 'doc_word',
               existing_type=sa.VARCHAR(length=50),
               comment='公文字 (例如：府、院、部)',
               existing_nullable=True)
    op.alter_column('documents', 'doc_class',
               existing_type=sa.VARCHAR(length=50),
               comment='公文類別 (例如：函、令、公告)',
               existing_nullable=True)
    op.alter_column('documents', 'assignee',
               existing_type=sa.VARCHAR(length=100),
               comment='承辦人',
               existing_nullable=True)
    op.alter_column('documents', 'user_confirm',
               existing_type=sa.BOOLEAN(),
               comment='使用者確認狀態',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'creator',
               existing_type=sa.VARCHAR(length=100),
               comment='建立者',
               existing_nullable=True)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否已軟刪除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'notes',
               existing_type=sa.TEXT(),
               comment='備註',
               existing_nullable=True)
    op.alter_column('documents', 'priority_level',
               existing_type=sa.VARCHAR(length=50),
               comment='速別 (例如：普通, 速件, 最速件)',
               existing_nullable=True)
    op.drop_constraint('documents_doc_number_key', 'documents', type_='unique')
    op.drop_index('idx_documents_created_at_desc', table_name='documents')
    op.drop_index('idx_documents_doc_date_status', table_name='documents')
    op.drop_index('idx_documents_sender_receiver', table_name='documents')
    op.drop_index('idx_documents_status_category', table_name='documents')
    op.drop_index('idx_documents_subject_search', table_name='documents')
    op.create_index(op.f('ix_documents_doc_date'), 'documents', ['doc_date'], unique=False)
    op.create_index(op.f('ix_documents_doc_number'), 'documents', ['doc_number'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_receiver'), 'documents', ['receiver'], unique=False)
    op.create_index(op.f('ix_documents_sender'), 'documents', ['sender'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_column('documents', 'priority')
    op.drop_column('documents', 'serial_number')
    op.drop_column('documents', 'auto_serial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('auto_serial', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('serial_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('priority', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_sender'), table_name='documents')
    op.drop_index(op.f('ix_documents_receiver'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_date'), table_name='documents')
    op.create_index('idx_documents_subject_search', 'documents', ['subject'], unique=False)
    op.create_index('idx_documents_status_category', 'documents', ['status', 'category'], unique=False)
    op.create_index('idx_documents_sender_receiver', 'documents', ['sender', 'receiver'], unique=False)
    op.create_index('idx_documents_doc_date_status', 'documents', [sa.text('doc_date DESC'), 'status'], unique=False)
    op.create_index('idx_documents_created_at_desc', 'documents', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('documents_doc_number_key', 'documents', ['doc_number'])
    op.alter_column('documents', 'priority_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='速別 (例如：普通, 速件, 最速件)',
               existing_nullable=True)
    op.alter_column('documents', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='備註',
               existing_nullable=True)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已軟刪除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'creator',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='建立者',
               existing_nullable=True)
    op.alter_column('documents', 'user_confirm',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='使用者確認狀態',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'assignee',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='承辦人',
               existing_nullable=True)
    op.alter_column('documents', 'doc_class',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='公文類別 (例如：函、令、公告)',
               existing_nullable=True)
    op.alter_column('documents', 'doc_word',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='公文字 (例如：府、院、部)',
               existing_nullable=True)
    op.alter_column('documents', 'contract_case',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='承攬案件名稱或編號',
               existing_nullable=True)
    op.alter_column('documents', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='公文分類 (例如：行政, 業務)',
               existing_nullable=True)
    op.alter_column('documents', 'send_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='發文日期 (用於區分 doc_date)',
               existing_nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最後更新時間',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='建立時間',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='公文內容摘要',
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='處理狀態 (例如：待處理, 已辦畢)',
               existing_nullable=True,
               existing_server_default=sa.text("'收文完成'::character varying"))
    op.alter_column('documents', 'receive_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='收文日期 (西元)',
               existing_nullable=True)
    op.alter_column('documents', 'doc_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='發文日期 (西元)',
               existing_nullable=True)
    op.alter_column('documents', 'receiver',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='受文單位',
               existing_nullable=True)
    op.alter_column('documents', 'sender',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='發文單位',
               existing_nullable=True)
    op.alter_column('documents', 'subject',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='主旨')
    op.alter_column('documents', 'doc_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='公文類型 (收文/發文)')
    op.alter_column('documents', 'doc_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='公文文號')
    op.drop_column('documents', 'source_serial_number')
    op.drop_column('documents', 'final_serial_number')
    op.create_table('calendar_sync_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='同步類型'),
    sa.Column('operation', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='操作類型'),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='關聯事件'),
    sa.Column('google_event_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Google 事件 ID'),
    sa.Column('status', postgresql.ENUM('PENDING', 'SYNCED', 'FAILED', 'CONFLICT', name='syncstatus'), autoincrement=False, nullable=False, comment='同步狀態'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='錯誤訊息'),
    sa.Column('sync_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='同步資料'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='建立時間'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name='calendar_sync_logs_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='calendar_sync_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calendar_sync_logs_pkey')
    )
    op.create_index('ix_calendar_sync_logs_id', 'calendar_sync_logs', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='事件標題'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='事件描述'),
    sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='事件地點'),
    sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='開始時間'),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='結束時間'),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='時區'),
    sa.Column('is_all_day', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否為全天事件'),
    sa.Column('recurrence_rule', sa.TEXT(), autoincrement=False, nullable=True, comment='重複規則 (RFC 5545 RRULE)'),
    sa.Column('recurrence_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='重複事件的父事件ID'),
    sa.Column('reminders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='提醒設定列表'),
    sa.Column('attendees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='與會者列表'),
    sa.Column('organizer_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='主辦人郵箱'),
    sa.Column('status', postgresql.ENUM('CONFIRMED', 'TENTATIVE', 'CANCELLED', name='eventstatus'), autoincrement=False, nullable=True, comment='事件狀態'),
    sa.Column('visibility', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='可見性'),
    sa.Column('google_event_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Google 事件 ID'),
    sa.Column('google_calendar_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Google 行事曆 ID'),
    sa.Column('google_sync_status', postgresql.ENUM('PENDING', 'SYNCED', 'FAILED', 'CONFLICT', name='syncstatus'), autoincrement=False, nullable=True, comment='Google 同步狀態'),
    sa.Column('google_last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Google 最後同步時間'),
    sa.Column('google_etag', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Google ETag for conflict detection'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='建立時間'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='更新時間'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='所屬使用者'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='建立者'),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='關聯公文'),
    sa.Column('contract_case_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='關聯承攬案件'),
    sa.ForeignKeyConstraint(['contract_case_id'], ['contract_projects.id'], name='calendar_events_contract_case_id_fkey'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='calendar_events_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='calendar_events_document_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='calendar_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calendar_events_pkey'),
    sa.UniqueConstraint('google_event_id', name='calendar_events_google_event_id_key')
    )
    op.create_index('ix_calendar_events_id', 'calendar_events', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('case_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'規劃中'::character varying"), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cases_pkey'),
    sa.UniqueConstraint('case_number', name='cases_case_number_key')
    )
    op.create_index('idx_cases_status_type', 'cases', ['status', 'case_type'], unique=False)
    # ### end Alembic commands ###
