"""Add vendor and project models with association table

Revision ID: 7970ab493fdc
Revises: e42b691ba7b2
Create Date: 2025-09-11 08:06:41.544511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7970ab493fdc'
down_revision: Union[str, Sequence[str], None] = 'e42b691ba7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False, comment='專案名稱'),
    sa.Column('project_code', sa.String(length=50), nullable=True, comment='專案編號'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年度'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='案件類別'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='案件狀態 (例如：進行中, 已結案)'),
    sa.Column('client_agency', sa.String(length=200), nullable=True, comment='委託單位'),
    sa.Column('contract_amount', sa.Float(), nullable=True, comment='合約金額'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='起始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='結束日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='專案描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最後更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_projects_category'), 'contract_projects', ['category'], unique=False)
    op.create_index(op.f('ix_contract_projects_id'), 'contract_projects', ['id'], unique=False)
    op.create_index(op.f('ix_contract_projects_project_code'), 'contract_projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_contract_projects_project_name'), 'contract_projects', ['project_name'], unique=False)
    op.create_index(op.f('ix_contract_projects_status'), 'contract_projects', ['status'], unique=False)
    op.create_index(op.f('ix_contract_projects_year'), 'contract_projects', ['year'], unique=False)
    op.create_table('doc_number_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, comment='年度'),
    sa.Column('doc_type', sa.String(length=10), nullable=False, comment='公文類型'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='目前的流水號'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_number_sequences_id'), 'doc_number_sequences', ['id'], unique=False)
    op.create_table('government_agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(length=200), nullable=False, comment='機關名稱'),
    sa.Column('agency_code', sa.String(length=50), nullable=True, comment='機關代碼'),
    sa.Column('agency_type', sa.String(length=50), nullable=True, comment='機關類型 (例如：中央, 地方)'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='聯絡人'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='電話'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='地址'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='電子郵件'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最後更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_agencies_agency_code'), 'government_agencies', ['agency_code'], unique=True)
    op.create_index(op.f('ix_government_agencies_agency_name'), 'government_agencies', ['agency_name'], unique=True)
    op.create_index(op.f('ix_government_agencies_id'), 'government_agencies', ['id'], unique=False)
    op.create_table('partner_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False, comment='廠商名稱'),
    sa.Column('vendor_code', sa.String(length=50), nullable=True, comment='廠商統一編號'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='聯絡人'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='電話'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='地址'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='電子郵件'),
    sa.Column('business_type', sa.String(length=100), nullable=True, comment='營業項目'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='合作評價 (例如 1-5)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最後更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_vendors_id'), 'partner_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_partner_vendors_vendor_code'), 'partner_vendors', ['vendor_code'], unique=True)
    op.create_index(op.f('ix_partner_vendors_vendor_name'), 'partner_vendors', ['vendor_name'], unique=True)
    op.create_table('project_vendor_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True, comment='廠商在專案中的角色 (主承包商/分包商/供應商)'),
    sa.Column('contract_amount', sa.Float(), nullable=True, comment='該廠商的合約金額'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='合作開始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='合作結束日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='合作狀態'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='關聯建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='關聯更新時間'),
    sa.ForeignKeyConstraint(['project_id'], ['contract_projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['partner_vendors.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'vendor_id')
    )
    op.drop_index('ix_document_case_relations_id', table_name='document_case_relations')
    op.drop_table('document_case_relations')
    op.drop_index('ix_cases_case_number', table_name='cases')
    op.drop_index('ix_cases_id', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_document_files_id', table_name='document_files')
    op.drop_table('document_files')
    op.drop_index('ix_calendar_events_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.add_column('documents', sa.Column('priority', sa.Integer(), nullable=True, comment='優先級 (數字)'))
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True, comment='公文內容摘要'))
    op.add_column('documents', sa.Column('assignee', sa.String(length=100), nullable=True, comment='承辦人'))
    op.add_column('documents', sa.Column('creator', sa.String(length=100), nullable=True, comment='建立者'))
    op.add_column('documents', sa.Column('notes', sa.Text(), nullable=True, comment='備註'))
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('documents', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('documents', 'contract_case',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_documents_aaron_plan_id', table_name='documents')
    op.drop_index('ix_documents_auto_serial', table_name='documents')
    op.drop_index('ix_documents_category', table_name='documents')
    op.drop_index('ix_documents_receive_date', table_name='documents')
    op.drop_index('ix_documents_send_date', table_name='documents')
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'aaron_plan_id')
    op.drop_column('documents', 'related_doc_id')
    op.drop_column('documents', 'notion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('notion_id', sa.VARCHAR(length=100), nullable=True))
    op.add_column('documents', sa.Column('related_doc_id', sa.INTEGER(), nullable=True))
    op.add_column('documents', sa.Column('aaron_plan_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['related_doc_id'], ['id'])
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.create_index('ix_documents_send_date', 'documents', ['send_date'], unique=False)
    op.create_index('ix_documents_receive_date', 'documents', ['receive_date'], unique=False)
    op.create_index('ix_documents_category', 'documents', ['category'], unique=False)
    op.create_index('ix_documents_auto_serial', 'documents', ['auto_serial'], unique=False)
    op.create_index('ix_documents_aaron_plan_id', 'documents', ['aaron_plan_id'], unique=False)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('documents', 'contract_case',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('documents', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('documents', 'subject',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'doc_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('documents', 'notes')
    op.drop_column('documents', 'creator')
    op.drop_column('documents', 'assignee')
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'priority')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=True),
    sa.Column('event_title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('event_date', sa.DATE(), nullable=False),
    sa.Column('event_time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('reminder_days', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_events_id', 'calendar_events', ['id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('upload_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_files_id', 'document_files', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('case_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_id', 'cases', ['id'], unique=False)
    op.create_index('ix_cases_case_number', 'cases', ['case_number'], unique=False)
    op.create_table('document_case_relations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_case_relations_id', 'document_case_relations', ['id'], unique=False)
    op.drop_table('project_vendor_association')
    op.drop_index(op.f('ix_partner_vendors_vendor_name'), table_name='partner_vendors')
    op.drop_index(op.f('ix_partner_vendors_vendor_code'), table_name='partner_vendors')
    op.drop_index(op.f('ix_partner_vendors_id'), table_name='partner_vendors')
    op.drop_table('partner_vendors')
    op.drop_index(op.f('ix_government_agencies_id'), table_name='government_agencies')
    op.drop_index(op.f('ix_government_agencies_agency_name'), table_name='government_agencies')
    op.drop_index(op.f('ix_government_agencies_agency_code'), table_name='government_agencies')
    op.drop_table('government_agencies')
    op.drop_index(op.f('ix_doc_number_sequences_id'), table_name='doc_number_sequences')
    op.drop_table('doc_number_sequences')
    op.drop_index(op.f('ix_contract_projects_year'), table_name='contract_projects')
    op.drop_index(op.f('ix_contract_projects_status'), table_name='contract_projects')
    op.drop_index(op.f('ix_contract_projects_project_name'), table_name='contract_projects')
    op.drop_index(op.f('ix_contract_projects_project_code'), table_name='contract_projects')
    op.drop_index(op.f('ix_contract_projects_id'), table_name='contract_projects')
    op.drop_index(op.f('ix_contract_projects_category'), table_name='contract_projects')
    op.drop_table('contract_projects')
    # ### end Alembic commands ###
