"""Initial database schema

Revision ID: e42b691ba7b2
Revises: 
Create Date: 2025-09-07 20:13:51.052422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42b691ba7b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False, comment='案件編號'),
    sa.Column('case_name', sa.String(length=500), nullable=False, comment='案件名稱'),
    sa.Column('case_type', sa.String(length=100), nullable=True, comment='案件類型'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='案件狀態'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='開始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='結束日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='案件描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(length=100), nullable=False, comment='公文文號'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='公文類型:發文/收文'),
    sa.Column('subject', sa.Text(), nullable=False, comment='主旨'),
    sa.Column('sender', sa.String(length=200), nullable=True, comment='發文機關'),
    sa.Column('receiver', sa.String(length=200), nullable=True, comment='收文機關'),
    sa.Column('doc_date', sa.Date(), nullable=True, comment='公文日期'),
    sa.Column('serial_number', sa.Integer(), nullable=True, comment='流水號'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='狀態'),
    sa.Column('notion_id', sa.String(length=100), nullable=True, comment='Notion記錄ID'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='分類：收文/發文'),
    sa.Column('doc_class', sa.String(length=50), nullable=True, comment='類別'),
    sa.Column('doc_word', sa.String(length=50), nullable=True, comment='字'),
    sa.Column('contract_case', sa.String(length=500), nullable=True, comment='承攬案件'),
    sa.Column('receive_date', sa.Date(), nullable=True, comment='收文日期'),
    sa.Column('send_date', sa.Date(), nullable=True, comment='發文日期'),
    sa.Column('user_confirm', sa.Boolean(), nullable=True, comment='使用者確認'),
    sa.Column('auto_serial', sa.Integer(), nullable=True, comment='自動流水號'),
    sa.Column('aaron_plan_id', sa.Integer(), nullable=True, comment='Aaron Plan 流水號'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='軟刪除標記'),
    sa.Column('related_doc_id', sa.Integer(), nullable=True, comment='關聯公文ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['related_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_aaron_plan_id'), 'documents', ['aaron_plan_id'], unique=False)
    op.create_index(op.f('ix_documents_auto_serial'), 'documents', ['auto_serial'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_doc_date'), 'documents', ['doc_date'], unique=False)
    op.create_index(op.f('ix_documents_doc_number'), 'documents', ['doc_number'], unique=True)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_receive_date'), 'documents', ['receive_date'], unique=False)
    op.create_index(op.f('ix_documents_send_date'), 'documents', ['send_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(length=500), nullable=False, comment='事件標題'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='事件日期'),
    sa.Column('event_time', sa.String(length=10), nullable=True, comment='事件時間'),
    sa.Column('event_type', sa.String(length=100), nullable=True, comment='事件類型:期限/會議/提醒'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否完成'),
    sa.Column('reminder_days', sa.Integer(), nullable=True, comment='提前提醒天數'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('document_case_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True, comment='關聯類型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_case_relations_id'), 'document_case_relations', ['id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='檔案名稱'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='檔案路徑'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='檔案大小'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='檔案類型'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='檔案雜湊值'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本號'),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_id'), 'document_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_files_id'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_document_case_relations_id'), table_name='document_case_relations')
    op.drop_table('document_case_relations')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_send_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_receive_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_auto_serial'), table_name='documents')
    op.drop_index(op.f('ix_documents_aaron_plan_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
