import type { ValidPath } from './types';

export const ICON_OPTIONS = [
  'DashboardOutlined', 'FileTextOutlined', 'FolderOutlined',
  'CalendarOutlined', 'BarChartOutlined', 'SettingOutlined',
  'TeamOutlined', 'UserOutlined', 'GlobalOutlined',
  'DatabaseOutlined', 'SafetyOutlined', 'BankOutlined',
  'ExperimentOutlined', 'ApartmentOutlined', 'RocketOutlined',
  'CloudServerOutlined', 'EnvironmentOutlined', 'ShopOutlined',
  'ProjectOutlined', 'NumberOutlined', 'ScheduleOutlined',
  'ApiOutlined', 'LinkOutlined', 'MonitorOutlined',
  'SecurityScanOutlined', 'EyeOutlined', 'LineChartOutlined',
  'GoogleOutlined', 'SendOutlined', 'PlusOutlined', 'FormOutlined',
] as const;

export const FALLBACK_VALID_PATHS: ValidPath[] = [
  { path: null, description: '(無 - 群組項目)' },
  { path: '/dashboard', description: '儀表板' },
  { path: '/documents', description: '公文管理' },
  { path: '/document-numbers', description: '發文字號管理' },
  { path: '/contract-cases', description: '承攬計畫' },
  { path: '/agencies', description: '機關管理' },
  { path: '/vendors', description: '廠商管理' },
  { path: '/staff', description: '承辦同仁' },
  { path: '/calendar', description: '行事曆' },
  { path: '/pure-calendar', description: '專案行事曆' },
  { path: '/reports', description: '統計報表' },
  { path: '/profile', description: '個人資料' },
  { path: '/admin/database', description: '資料庫管理' },
  { path: '/admin/user-management', description: '使用者管理' },
  { path: '/admin/site-management', description: '網站管理' },
  { path: '/admin/permissions', description: '權限管理' },
  { path: '/admin/dashboard', description: '管理員面板' },
  { path: '/admin/backup', description: '備份管理' },
  { path: '/admin/deployment', description: '部署管理' },
  { path: '/admin/ai-assistant', description: 'AI 助理管理' },
  { path: '/ai/knowledge-graph', description: '公文圖譜' },
  { path: '/ai/code-graph', description: '代碼圖譜' },
  { path: '/ai/db-graph', description: '資料庫圖譜' },
  { path: '/system', description: '系統監控' },
  { path: '/google-auth-diagnostic', description: 'Google認證診斷' },
  { path: '/unified-form-demo', description: '統一表單示例' },
  { path: '/api-mapping', description: 'API對應表' },
  { path: '/api/docs', description: 'API文件' },
  { path: '/taoyuan/dispatch', description: '派工管理' },
];
