#!/usr/bin/env bash
# install-hooks.sh — 安裝所有共享 git hook 到本地 .git/hooks/
#
# 用途：團隊成員 clone repo 後執行一次，將 scripts/hooks/ 下的 hook 腳本
# 串接或安裝到 .git/hooks/，使其生效。
#
# 使用：bash scripts/hooks/install-hooks.sh

set -euo pipefail

# ⚠️ 2026-08-29 實測：本腳本**從來沒有被跑過**（或跑過但 pre-commit 後來被重寫）。
# 當日 `scripts/hooks/` 的 3 支守衛，**沒有一支被任何已安裝的 hook 呼叫**。
#
# 而查下去比「沒安裝」嚴重：`.git/hooks/pre-commit` 的「檢查 5 Secret scan」
# 依賴 `scripts/check-secrets.cjs`，**那個檔案不存在** ⇒ `if [ -f ... ]`
# 為 false ⇒ **整段靜靜跳過**，而 hook 印出的是一切正常。
#
# 實測：把含 `sk-proj-...` 的 `.env.LEAKTEST` 加進暫存 ⇒
# **pre-commit exit 0，輸出裡連提都沒提**。⇒ 提交時完全沒有 secret 掃描。
#
# 已直接改 `.git/hooks/pre-commit` 改用本目錄的 `pre-commit-secret-guard.sh`，
# 並讓「守衛檔不見」時**出聲 exit 1** 而不是沉默跳過。
#
# ⚠️ `.git/hooks/` **不在版控**（git 的設計）⇒ 那個修正只存在於這台機器。
# **換機器或重新 clone 的人必須跑這支**：
#
#     bash scripts/hooks/install-hooks.sh
#
# 判準（待辦 B10 自己寫的那句）：「這支東西壞掉的時候，會有人知道嗎？」
# —— 答案曾經是「不會」，因為它壞掉的樣子就是「什麼都沒印」。


PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
SCRIPTS_HOOKS="$PROJECT_ROOT/scripts/hooks"

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo "✖ 未偵測到 .git/ 目錄；請在 CK_Missive repo 根目錄執行"
    exit 1
fi

mkdir -p "$HOOKS_DIR"

# pre-commit：串接既有 hook（若存在）+ secret-guard
PRE_COMMIT="$HOOKS_DIR/pre-commit"
if [ -f "$PRE_COMMIT" ] && ! grep -q "pre-commit-secret-guard.sh" "$PRE_COMMIT"; then
    echo "偵測到既有 pre-commit hook，追加 secret-guard 呼叫"
    cat >> "$PRE_COMMIT" <<'EOF'

# --- Auto-appended by install-hooks.sh (secret guard) ---
if [ -x "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" ]; then
    bash "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" || exit $?
fi
EOF
elif [ ! -f "$PRE_COMMIT" ]; then
    cat > "$PRE_COMMIT" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh
if [ -x "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" ]; then
    bash "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" || exit $?
fi
EOF
    chmod +x "$PRE_COMMIT"
fi

echo "✓ pre-commit hook 已安裝/更新（含 secret-guard）"
echo "  驗證：嘗試 git add .env 然後 git commit —應被阻擋"

# Pattern YAML type guard（2026-04-24 ADR-0028）
if ! grep -q "pre-commit-pattern-yaml-guard.sh" "$PRE_COMMIT"; then
    echo "追加 pattern YAML type guard"
    cat >> "$PRE_COMMIT" <<'EOF'

# --- Auto-appended by install-hooks.sh (pattern YAML type guard, ADR-0028) ---
if [ -x "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-pattern-yaml-guard.sh" ]; then
    bash "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-pattern-yaml-guard.sh" || exit $?
fi
EOF
fi

echo "✓ pre-commit hook 含 pattern-yaml-guard"
