#!/usr/bin/env bash
# install-hooks.sh — 安裝所有共享 git hook 到本地 .git/hooks/
#
# 用途：團隊成員 clone repo 後執行一次，將 scripts/hooks/ 下的 hook 腳本
# 串接或安裝到 .git/hooks/，使其生效。
#
# 使用：bash scripts/hooks/install-hooks.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
SCRIPTS_HOOKS="$PROJECT_ROOT/scripts/hooks"

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo "✖ 未偵測到 .git/ 目錄；請在 CK_Missive repo 根目錄執行"
    exit 1
fi

mkdir -p "$HOOKS_DIR"

# pre-commit：串接既有 hook（若存在）+ secret-guard
PRE_COMMIT="$HOOKS_DIR/pre-commit"
if [ -f "$PRE_COMMIT" ] && ! grep -q "pre-commit-secret-guard.sh" "$PRE_COMMIT"; then
    echo "偵測到既有 pre-commit hook，追加 secret-guard 呼叫"
    cat >> "$PRE_COMMIT" <<'EOF'

# --- Auto-appended by install-hooks.sh (secret guard) ---
if [ -x "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" ]; then
    bash "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" || exit $?
fi
EOF
elif [ ! -f "$PRE_COMMIT" ]; then
    cat > "$PRE_COMMIT" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh
if [ -x "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" ]; then
    bash "$(git rev-parse --show-toplevel)/scripts/hooks/pre-commit-secret-guard.sh" || exit $?
fi
EOF
    chmod +x "$PRE_COMMIT"
fi

echo "✓ pre-commit hook 已安裝/更新（含 secret-guard）"
echo "  驗證：嘗試 git add .env 然後 git commit —應被阻擋"
